Rename cargo.toml to Cargo.toml (fix build on Linux)
On Linux, because of its case-sensibility, it fails to build.
error: no matching package named bevy_granite found
For this, I renamed cargo.toml.